language: python
python:
    - "3.6"
cache: pip

before_install:

    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda

install:
    - conda env create -f environment.yml
    - source activate cogni
    - pip install -e .

script:
    - pytest cognigraph/ --cov
    - flake8 --count cognigraph

after_success:
    - codecov

